[package]
name = "fydia-router"
version = "0.0.1"
edition = "2018"

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-struct = { path="../fydia-struct" }
fydia-sql = { path="../fydia-sql" }
fydia-utils = { path="../fydia-utils" }
fydia-crypto = { path="../fydia-crypto" }
fydia-dispatcher = { path="../fydia-dispatcher" }
tokio = { version="1.15", default-features=false }
futures = "0.3.19"
futures-util = "0.3.18"
time = "0.3.5"
chrono = "0.4.19"
axum = {version = "0.4.4",  features = ["ws", "headers"]}
http = "0.2.6"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
base64 = "0.13"
mime = "0.3.12"
multer = "2.0.2"
serde_json = "1.0.75"
serde = "1.0.133"
reqwest = "0.11.9"
rayon = "1.5.1"
infer = "0.6.0"
mime_guess = "2.0.3"
tracing = "0.1.29"
tower-http = {version = "0.2.0", features=["trace"]}
tower = "0.4.11"
rand = "0.8.4"
parking_lot =  {version = "0.11.2"}
hyper = "0.14.16"
flume = "0.10.10"

[dev-dependencies]
tokio-tungstenite = "0.16.1"
reqwest = "0.11.9"
url = "2.2.2"