[package]
name = "fydia-router"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-struct = { path="../fydia-struct" }
fydia-sql = { path="../fydia-sql" }
fydia-utils = { path="../fydia-utils" }
fydia-crypto = { path="../fydia-crypto" }
fydia-dispatcher = { path="../fydia-dispatcher" }
tokio = { version="1.15", default-features=false }
futures = "0.3.18"
futures-util = "0.3.18"
time = "0.3.5"
chrono = "0.4.19"
axum = {version = "0.4.2",  features = ["ws", "headers"]}
http = "0.2.5"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
base64 = "0.13"
mime = "0.3.12"
multer = "2.0.0"
serde_json = "1.0.73"
serde = "1.0.132"
reqwest = "0.11.5"
rayon = "1.5.1"
infer = "0.5.0"
mime_guess = "2.0.3"
tracing = "0.1.29"
tower-http = {version = "0.2.0", features=["trace"]}
tower = "0.4.11"
rand = "0.8.4"
parking_lot =  {version = "0.11.2", features = ["deadlock_detection"]}
hyper = "0.14.16"
async-channel = "1.6.1"