[package]
name = "fydia-router"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-struct = { path="../fydia-struct" }
fydia-sql = { path="../fydia-sql" }
fydia-utils = { path="../fydia-utils" }
fydia-crypto = { path="../fydia-crypto" }
fydia-dispatcher = { path="../fydia-dispatcher" }
tokio = { version="1.13", default-features=false }
futures = "0.3.15"
tokio-tungstenite = "0.15.0"
time = "0.3.4"
chrono = "0.4.19"
gotham = "0.6.0"
gotham_derive = "0.6.0"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
sha1 = "0.6"
base64 = "0.13"
mime = "0.3.12"
multer = "2.0.0"
serde_json = "1.0.68"
serde = "1.0.126"
reqwest = "0.11.5"
rayon = "1.5.1"
infer = "0.5.0"
mime_guess = "2.0.3"
anyhow = "1.0.44"