[package]
name = "fydia-router"
version = "0.0.1"
edition = "2018"

[features]
flutter_client = ["rust-embed"]


[dependencies]
fydia-config = { path = "../fydia-config" }
fydia-struct = { path = "../fydia-struct" }
fydia-sql = { path = "../fydia-sql" }
fydia-utils = { path = "../fydia-utils" }
fydia-crypto = { path = "../fydia-crypto" }
fydia-dispatcher = { path = "../fydia-dispatcher" }
tokio = { version = "1.17.0", default-features = false }
futures = "0.3.21"
chrono = "0.4.19"
axum = { version = "0.5.1", features = ["ws", "headers"] }
http = "0.2.6"
log = "0.4.0"
mime = "0.3.16"
multer = "2.0.2"
serde_json = "1.0.79"
serde = "1.0.136"
infer = "0.8.0"
mime_guess = "2.0.4"
tracing = "0.1.32"
tower-http = { version = "0.3.0", features = ["trace"] }
tower = "0.4.12"
parking_lot = { version = "0.12.0" }
flume = "0.10.12"
rust-embed = { version = "6.3.0", optional = true }


[dev-dependencies]
fydia-libtest = { path = "../fydia-libtest" }
