[package]
name = "fydia-router"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-struct = { path="../fydia-struct" }
fydia-sql = { path="../fydia-sql" }
fydia-utils = { path="../fydia-utils" }
fydia-crypto = { path="../fydia-crypto" }
fydia-dispatcher = { path="../fydia-dispatcher" }
tokio = { version="1.12", default-features=false }
futures = "0.3.17"
futures-util = "0.3.17"
tokio-tungstenite = "0.16.0"
time = "0.3.5"
chrono = "0.4.19"
axum = {version = "0.3.2",  features = ["ws", "headers"]}
http = "0.2.5"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
sha1 = "0.6"
base64 = "0.13"
mime = "0.3.12"
multer = "2.0.0"
serde_json = "1.0.68"
serde = "1.0.126"
reqwest = "0.11.5"
rayon = "1.5.1"
infer = "0.5.0"
mime_guess = "2.0.3"
tracing = "0.1"
tower-http = {version = "0.1.2", features=["trace"]}
tower = "0.4.10"
rand = "0.8.4"