//! SeaORM Entity. Generated by sea-orm-codegen 0.2.3

use fydia_struct::{
    channel::{Channel, ChannelType},
    server::ServerId,
};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub parent_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub channel_type: Option<String>,
}

impl Model {
    pub fn from_channel(channel: Channel) -> Self {
        Self {
            id: channel.id,
            parent_id: channel.server_id.short_id,
            name: channel.name,
            description: Some(channel.description),
            channel_type: Some(channel.channel_type.to_string()),
        }
    }
    pub fn to_channel(&self) -> Option<Channel> {
        let channel_type = match self.channel_type.clone() {
            Some(e) => ChannelType::from_string(e),
            None => return None,
        };
        Some(Channel {
            id: self.id.clone(),
            name: self.name.clone(),
            server_id: ServerId::new(self.parent_id.clone()),
            channel_type,
            description: self.description.clone().unwrap_or_default(),
        })
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
