[package]
name = "fydia-sql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-struct = { path="../fydia-struct" }
fydia-utils = { path="../fydia-utils" }
sqlx = { version="0.5.9", default-features=false, features=[
    "runtime-tokio-rustls",
    "all-databases",
    "chrono",
    "time",
] }

sea-orm =  {version = "0.3.0", features = [ "sqlx-all", "runtime-tokio-rustls", "macros" ]}
futures = "0.3.15"
gotham = "0.6.0"
gotham_derive = "0.6.0"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
async-trait = "0.1.50"
serde = "1.0.126"
serde_json = "1.0.68"
tokio = "1.12.0"
