[package]
name = "fydia-sql"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.56"
fydia-config = { path = "../fydia-config" }
fydia-crypto = { path = "../fydia-crypto" }
fydia-struct = { path = "../fydia-struct" }
fydia-utils = { path = "../fydia-utils" }
log = "0.4.16"

sea-orm = { version = "0.8.0", default-features = false, features = [
    "sqlx-mysql",
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }

tokio = { version = "1.19.2", default-features = false, features = [
    "rt",
    "macros",
] }

entity = { path = "entity" }
migration = { path = "migration" }
