[package]
name = "fydia-sql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-config = { path="../fydia-config" }
fydia-crypto = { path="../fydia-crypto" }
fydia-struct = { path="../fydia-struct" }
fydia-utils = { path="../fydia-utils" }
sqlx = { version="0.5.10", default-features=false, features=[
    "runtime-tokio-rustls",
    "all-databases",
    "chrono",
    "time",
] }

sea-orm =  {version = "0.6.0", features = [ "sqlx-all", "runtime-tokio-rustls", "macros" ]}
futures = "0.3.21"
logger = { git="https://github.com/Rheydskey/logger.git", branch="master" }
async-trait = "0.1.52"
serde = "1.0.136"
serde_json = "1.0.79"
tokio = {version = "1.16.1", features=["rt", "macros"]}
