[package]
name = "fydia-config"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-utils = { path = "../fydia-utils" }
toml = "0.7.2"
reqwest = "0.11.14"
log = "0.4.17"
