[config]
url = "ee"
port = 1200

[tests.create_a_user]
test = [
    { type = "http", method = "POST", url = "/user/create", headers = [
        "token",
        "__TOKEN__",
    ], body = """{"eee","eee"}""", status_response = 200, body_response = "eee" },
    { type = "websocket", headers = [] },
]
set_value = [{ name = "__TOKEN__", path = "content" }]
