[package]
name = "fydia"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.3.2"
axum-debug = "0.2.1"
gotham = "0.6.0"
gotham_derive = "0.6.0"
tokio = { version="1.12.0", default-features=false, features=["rt", "macros"] }
fydia-router = { path="../fydia-router" }
fydia-config = { path="../fydia-config" }