//! `SeaORM` Entity. Generated by sea-orm-codegen 0.6.0
#![feature(type_alias_impl_trait)]

pub mod prelude;

pub mod channels;
pub mod direct_message;
pub mod direct_message_members;
pub mod members;
pub mod messages;
pub mod permission;
pub mod roles;
pub mod server;
pub mod user;
