[package]
name = "fydia-struct"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-crypto =  {path = "../fydia-crypto"}
fydia-utils = { path="../fydia-utils" }
tokio = { version="1.15", default-features=false }
async-trait = "0.1.52"
futures = "0.3.19"
serde = { version="1.0.135", features=["derive"] }
serde_json = { version="1.0.78" }
chrono = "0.4.19"
url = "2.2.2"
reqwest = {version = "0.11.9",features = ["blocking"]}
hyper = "0.14.16"
http = "0.2.6"
mime = "0.3.16"
axum = {version = "0.4.4", features=["headers"]}