[package]
name = "fydia-struct"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fydia-crypto = { path = "../fydia-crypto" }
fydia-utils = { path = "../fydia-utils" }
tokio = { version = "1.17", default-features = false }
async-trait = "0.1.53"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.81" }
chrono = "0.4.19"
url = "2.2.2"
reqwest = { version = "0.11.10", features = ["blocking"] }
hyper = "0.14.18"
http = "0.2.6"
mime = "0.3.16"
axum = { version = "0.5.0", features = ["headers"] }
