[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
fydia-struct = { path = "../../fydia-struct" }
fydia-utils = { path = "../../fydia-utils" }
