name: Fydia Builder

on: 
  push

jobs:
  buildflutter:
    name: Build Fydia with Flutter client
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Clone fydiapackages
        uses: actions/checkout@v1
        with:
          ref: "origin/main"
          repository: "fydia/fydiapackages"
          path: "./fydia/fydia-router/fydiapackages"
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests
      - name: Fydia without Flutter Client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p fydia --release
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: "/home/runner/work/fydia/fydia/target/release/fydia"
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Linux-release"
          path: "/home/runner/work/fydia/fydia/target/release/fydia"
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1 
      - name: Fydia with Flutter Client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p fydia --features flutter_client --release
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: "/home/runner/work/fydia/fydia/target/release/fydia"
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Linux-flutter-release"
          path: "/home/runner/work/fydia/fydia/target/release/fydia"
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1hr
