name: Fydia Builder

on: "push"

jobs:
  buildflutter:
    name: Build Fydia with Flutter client
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Clone fydiapackages
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: "fydia"
          repository: "fydiapackages"
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Move to fydiarouter
        run: mv fydiapackages ./fydia-router
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p fydia --features flutter_client --release
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: "/home/runner/work/fydia/fydia/target/release/fydia"
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Linux-release"
          path: "/home/runner/work/fydia/fydia/target/release/fydia"
  build:
    name: Build Fydia
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p fydia --release
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: "/home/runner/work/fydia/fydia/target/release/fydia"
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Linux-release"
          path: "/home/runner/work/fydia/fydia/target/release/fydia"
  tests:
    name: Tests Fydia
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1hr
